error: there is no argument named `foo`

 --> mutant.rs:3:12

  |

3 | format ! ( concat ! ( "{foo}" ) ) ;

  |            ^^^^^^^^^^^^^^^^^^^^

  |

  = note: did you intend to capture a variable `foo` from the surrounding scope?

  = note: to avoid ambiguity, `format_args!` cannot capture variables when the format string is expanded from a macro

  = note: this error originates in the macro `concat` (in Nightly builds, run with -Z macro-backtrace for more info)



thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1573:17

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



error: internal compiler error: unexpected panic



note: the compiler unexpectedly panicked. this is a bug.



note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md



note: rustc 1.54.0-nightly (dbe459ded 2021-06-02) running on x86_64-unknown-linux-gnu



note: compiler flags: -Z mir-opt-level=3 -Z new-llvm-pass-manager=yes -Z unsound-mir-opts=yes -Z polonius=yes -Z polymorphize=yes -C debuginfo=2 -C opt-level=3 --crate-type staticlib



query stack during panic:

end of query stack

error: aborting due to previous error



